set -g status-style "fg=white,bg=colour234"
set -g status-left "#[fg=green,bold]#S #[fg=white]| "
set -g status-right "#{?client_prefix,#[reverse] WAIT #[noreverse] ,}#(~/.config/tmux/tmux_battery.sh) #[fg=white]| #[fg=cyan]%-d %b %Y #[fg=white]| #[fg=cyan]%H:%M"
setw -g window-status-format "#[fg=colour244] #I:#W#F "
setw -g window-status-current-format "#[fg=colour166,bold] #I:#W#F "
set -g pane-border-style "fg=colour238"
set -g pane-active-border-style "fg=colour166"
set -g message-style "fg=white,bg=colour166,bold"
set -g display-panes-active-colour colour166
set -g display-panes-colour colour244
setw -g clock-mode-colour colour166
