set -g status-style "fg=colour235,bg=colour231"
set -g status-left "#[fg=colour22,bold]#S #[fg=colour245]| "
set -g status-right "#{?client_prefix,#[reverse] WAIT #[noreverse] ,}#(~/.config/tmux/tmux_battery.sh) #[fg=colour245]| #[fg=colour26]%-d %b %Y #[fg=colour245]| #[fg=colour26]%H:%M"
setw -g window-status-format "#[fg=colour243] #I:#W#F "
setw -g window-status-current-format "#[fg=colour26,bold] #I:#W#F "
set -g pane-border-style "fg=colour252"
set -g pane-active-border-style "fg=colour26"
set -g message-style "fg=colour231,bg=colour26,bold"
set -g display-panes-active-colour colour26
set -g display-panes-colour colour243
setw -g clock-mode-colour colour26
