# Light theme
set -g status-style "fg=colour238,bg=colour254"
set -g @off_status_style "fg=colour244,bg=colour252"
set -g status-left "#[fg=colour22,bold]#S #[fg=colour238]| "
set -g status-right "#{?client_prefix,#[reverse] WAIT #[noreverse] ,}#[fg=colour238]#[fg=colour24]%-d %b %Y #[fg=colour238]| #[fg=colour24]%H:%M"
setw -g window-status-format "#[fg=colour244] #I:#W#F "
setw -g window-status-current-format "#[fg=colour166,bold] #I:#W#F "
set -g pane-border-style "fg=colour252"
set -g pane-active-border-style "fg=colour166"
set -g message-style "fg=white,bg=colour166,bold"
