set -g status-style "fg=white,bg=default"
set -g @off_status_style "fg=colour244,bg=colour237"
set -g status-left "#[fg=green,bold]#S #[fg=white]| "
set -g status-right "#{?client_prefix,#[reverse] WAIT #[noreverse] ,}#[fg=white]#[fg=cyan]%-d %b %Y #[fg=white]| #[fg=cyan]%H:%M"
setw -g window-status-format "#[fg=colour244] #I:#W#F "
setw -g window-status-current-style "fg=colour166,bold,bg=default"
setw -g window-status-current-format " #I:#W#F "

set -g pane-border-lines heavy
set -g pane-border-style "fg=colour238"
set -g pane-active-border-style "fg=colour166"

set -g message-style "fg=white,bg=colour166,bold"
set -g mode-style "fg=colour166,bg=colour237,bold"
