theme = "catppuccin_macchiato"

[editor]
true-color = true
line-number = "relative"
auto-format = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.normal]
# C-f = [":new", ":insert-output lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw"]
C-f = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
C-b = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
"C-n" = ["move_prev_word_start", "move_next_word_end", "search_selection", "extend_search_next"]
esc = ["collapse_selection", "keep_primary_selection"]

