theme = "catppuccin_macchiato"

[editor]
true-color = true
line-number = "relative"
auto-format = true
auto-save = true
bufferline = "multiple"
# terminal.command = "xterm"
# terminal.args = ["-e"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.normal]
C-f = [":new", ":insert-output ~/.config/helix/lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw"]
C-b = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-s = ":w"
S-l = ":buffer-next"
S-h = ":buffer-previous"
C-n = ["move_prev_word_start", "move_next_word_end", "search_selection", "extend_search_next"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
l = ":lsp-restart"

[keys.insert]
C-s = [":w", "normal_mode"]
