theme = "catppuccin_macchiato"

[editor]
true-color = true
line-number = "relative"
auto-format = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-f = [":new", ":insert-output lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw"]
C-b = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
